apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  JWT_SECRET: "myfancysecret"
  ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_CHANNEL: "log_channel"
  USERS_API_ADDRESS: "http://users-api:8083"
  AUTH_API_PORT: "8080"
  TODO_API_PORT: "8082"
